# Generated by Django 5.2 on 2025-05-29 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_plan', '0006_alter_productionplan_drawing_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing', models.FileField(blank=True, null=True, upload_to='techcards/%Y/%m/%d/', verbose_name='Операционно-технологическая карта')),
                ('route_description', models.TextField(help_text='Подробное описание технологического маршрута', verbose_name='Маршрут/операции')),
                ('steel_grade', models.CharField(max_length=100, verbose_name='Марка стали')),
                ('total_quantity', models.PositiveIntegerField(verbose_name='Общее количество изделий по плану')),
                ('production_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='techcard', to='production_plan.productionplan', verbose_name='Производственный план')),
            ],
        ),
    ]
