# Generated by Django 5.2 on 2025-05-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techcard',
            name='route_description',
        ),
        migrations.AddField(
            model_name='techcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='techcard',
            name='technological_process',
            field=models.TextField(default='', help_text='Последовательность операций с параметрами', verbose_name='Технологический маршрут'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='drawing',
            field=models.FileField(blank=True, null=True, upload_to='techcards/%Y/%m/%d/', verbose_name='Чертеж/Схема'),
        ),
        migrations.AlterField(
            model_name='techcard',
            name='total_quantity',
            field=models.PositiveIntegerField(verbose_name='План выпуска (шт)'),
        ),
    ]
