# Generated by Django 5.2 on 2025-05-30 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcard', '0002_remove_techcard_route_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechCardStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('equipment', models.CharField(max_length=200, verbose_name='Оборудование')),
                ('operation_time', models.DurationField(blank=True, null=True, verbose_name='Время операции')),
                ('instructions', models.TextField(blank=True, verbose_name='Инструкция')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок этапа')),
                ('techcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='techcard.techcard', verbose_name='Техкарта')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
