# Generated by Django 5.2 on 2025-05-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcard', '0003_techcardstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techcard',
            name='steel_grade',
            field=models.CharField(blank=True, default='Н/Д', help_text='Оставьте пустым, если марка стали не имеет значения', max_length=100, verbose_name='Марка стали'),
        ),
    ]
