# Generated by Django 5.2 on 2025-06-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcard', '0004_alter_techcard_steel_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techcard',
            name='total_quantity',
            field=models.PositiveIntegerField(verbose_name='Количество (шт)'),
        ),
    ]
