# Generated by Django 5.2 on 2025-05-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('operator', 'Оператор'), ('master', 'Мастер'), ('director', 'Директор'), ('admin', 'Администратор')], default='operator', max_length=20, verbose_name='Роль'),
        ),
    ]
