# Generated by Django 5.2 on 2025-04-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_user_id_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('operator', 'Operator'), ('master', 'Master'), ('director', 'Director'), ('admin', 'Administrator')], max_length=255),
        ),
    ]
