# Generated by Django 5.2 on 2025-05-09 17:23

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата смены')),
                ('shift_type', models.CharField(choices=[('day', 'Дневная смена (08:00-20:00)'), ('night', 'Ночная смена (20:00-08:00)')], default='day', max_length=10, verbose_name='Тип смены')),
                ('machine_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер станка')),
                ('planned_quantity', models.PositiveIntegerField(default=0, verbose_name='Плановое количество')),
                ('actual_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Фактическое количество')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('cancelled', 'Отменено')], db_index=True, default='planned', max_length=20, verbose_name='Статус задания')),
                ('drawing', models.FileField(blank=True, null=True, upload_to='drawings/%Y/%m/%d/', verbose_name='Чертеж')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_shift_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Завершил')),
                ('operator', models.ForeignKey(limit_choices_to={'groups__name': 'Operators'}, on_delete=django.db.models.deletion.PROTECT, related_name='shift_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='production_plan.productionplan', verbose_name='План производства')),
            ],
            options={
                'verbose_name': 'Сменное задание',
                'verbose_name_plural': 'Сменные задания',
                'ordering': ['-shift_date', 'shift_type', 'machine_number'],
                'indexes': [models.Index(fields=['shift_date'], name='shift_assig_shift_d_5fe4c1_idx'), models.Index(fields=['status'], name='shift_assig_status_2e6b14_idx'), models.Index(fields=['production_plan'], name='shift_assig_product_2690a9_idx')],
                'unique_together': {('shift_date', 'shift_type', 'machine_number')},
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignmentArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.PositiveIntegerField(verbose_name='ID оригинального задания')),
                ('shift_date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Дата смены')),
                ('shift_type', models.CharField(choices=[('day', 'Дневная смена (08:00-20:00)'), ('night', 'Ночная смена (20:00-08:00)')], default='day', max_length=10, verbose_name='Тип смены')),
                ('machine_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер станка')),
                ('planned_quantity', models.PositiveIntegerField(default=0, verbose_name='Плановое количество')),
                ('actual_quantity', models.PositiveIntegerField(verbose_name='Фактическое количество')),
                ('completion_time', models.DurationField(blank=True, null=True, verbose_name='Время выполнения')),
                ('quality_status', models.BooleanField(default=False, verbose_name='Пройдена проверка качества')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата архивации')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
                ('production_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_assignments', to='production_plan.productionplan', verbose_name='План производства')),
            ],
            options={
                'verbose_name': 'Архивное задание',
                'verbose_name_plural': 'Архив заданий',
                'ordering': ['-archived_at'],
                'indexes': [models.Index(fields=['original_id'], name='shift_assig_origina_0ccf59_idx'), models.Index(fields=['shift_date'], name='shift_assig_shift_d_ae0cc5_idx'), models.Index(fields=['operator'], name='shift_assig_operato_df6aed_idx')],
            },
        ),
    ]
