# Generated by Django 5.2 on 2025-05-06 20:45

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата смены')),
                ('shift_type', models.CharField(choices=[('day', 'Дневная смена (08:00-20:00)'), ('night', 'Ночная смена (20:00-08:00)')], default='day', max_length=10, verbose_name='Тип смены')),
                ('machine_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер станка')),
                ('planned_quantity', models.PositiveIntegerField(default=0, verbose_name='Плановое количество')),
                ('actual_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Фактическое количество')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('cancelled', 'Отменено')], db_index=True, default='planned', max_length=20, verbose_name='Статус задания')),
                ('drawing', models.FileField(blank=True, null=True, upload_to='drawings/%Y/%m/%d/', verbose_name='Чертеж')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
            ],
            options={
                'verbose_name': 'Сменное задание',
                'verbose_name_plural': 'Сменные задания',
                'ordering': ['-shift_date', 'shift_type', 'machine_number'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignmentArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.PositiveIntegerField(verbose_name='ID оригинального задания')),
                ('shift_date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Дата смены')),
                ('shift_type', models.CharField(choices=[('day', 'Дневная смена (08:00-20:00)'), ('night', 'Ночная смена (20:00-08:00)')], default='day', max_length=10, verbose_name='Тип смены')),
                ('machine_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер станка')),
                ('planned_quantity', models.PositiveIntegerField(default=0, verbose_name='Плановое количество')),
                ('actual_quantity', models.PositiveIntegerField(verbose_name='Фактическое количество')),
                ('completion_time', models.DurationField(blank=True, null=True, verbose_name='Время выполнения')),
                ('quality_status', models.BooleanField(default=False, verbose_name='Пройдена проверка качества')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата архивации')),
            ],
            options={
                'verbose_name': 'Архивное задание',
                'verbose_name_plural': 'Архив заданий',
                'ordering': ['-archived_at'],
            },
        ),
    ]
