# Generated by Django 5.2 on 2025-04-12 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('machine_number', models.IntegerField()),
                ('order', models.CharField(max_length=255)),
                ('part', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('part_blueprint', models.FileField(upload_to='part_blueprints/')),
                ('execution_status', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shift Assignment',
                'verbose_name_plural': 'Shift Assignments',
            },
        ),
    ]
