# Generated by Django 5.2 on 2025-04-15 19:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftassignment',
            options={'ordering': ['-date', 'machine_number'], 'verbose_name': 'Сменное задание', 'verbose_name_plural': 'Сменные задания'},
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='customer',
            field=models.CharField(max_length=255, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='execution_status',
            field=models.BooleanField(default=False, verbose_name='Статус выполнения'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='machine_number',
            field=models.IntegerField(verbose_name='Номер станка'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='order',
            field=models.CharField(max_length=255, verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='part',
            field=models.CharField(max_length=255, verbose_name='Деталь'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='part_blueprint',
            field=models.FileField(upload_to='part_blueprints/', verbose_name='Чертеж детали'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.CreateModel(
            name='ShiftAssignmentArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.PositiveIntegerField(verbose_name='ID оригинального задания')),
                ('customer', models.CharField(max_length=255, verbose_name='Клиент')),
                ('date', models.DateField(verbose_name='Дата выполнения')),
                ('machine_number', models.IntegerField(verbose_name='Номер станка')),
                ('order', models.CharField(max_length=255, verbose_name='Заказ')),
                ('part', models.CharField(max_length=255, verbose_name='Деталь')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('part_blueprint', models.FileField(upload_to='archived_blueprints/', verbose_name='Чертеж детали')),
                ('actual_quantity', models.IntegerField(blank=True, null=True, verbose_name='Фактическое количество')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата завершения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('quality_check', models.BooleanField(default=False, verbose_name='Проверка качества')),
                ('shift_duration', models.DurationField(blank=True, null=True, verbose_name='Длительность смены')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Архивная смена',
                'verbose_name_plural': 'Архив смен',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['original_id'], name='shift_assig_origina_0ccf59_idx'), models.Index(fields=['date'], name='shift_assig_date_c443bd_idx'), models.Index(fields=['operator'], name='shift_assig_operato_df6aed_idx')],
            },
        ),
    ]
