# Generated by Django 5.2 on 2025-05-05 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_plan', '0002_initial'),
        ('shift_assignment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_assignments', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='production_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_assignments', to='production_plan.productionplan', verbose_name='План производства'),
        ),
        migrations.AddField(
            model_name='shiftassignmentarchive',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='Пользователь, выполнивший задание', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_assignments', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='shiftassignmentarchive',
            name='production_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_assignments', to='production_plan.productionplan', verbose_name='Связанный план производства'),
        ),
        migrations.AddIndex(
            model_name='shiftassignmentarchive',
            index=models.Index(fields=['original_id'], name='shift_assig_origina_0ccf59_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignmentarchive',
            index=models.Index(fields=['operator'], name='shift_assig_operato_df6aed_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignmentarchive',
            index=models.Index(fields=['completed_at'], name='shift_assig_complet_174747_idx'),
        ),
    ]
