# Generated by Django 5.2 on 2025-05-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftassignment',
            name='status',
            field=models.CharField(choices=[('assignment', 'Задание на смену'), ('completed', 'Выполненное задание')], db_index=True, default='assignment', max_length=20, verbose_name='Статус задания'),
        ),
    ]
