# Generated by Django 5.2 on 2025-05-06 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_plan', '0002_initial'),
        ('shift_assignment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='operator',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Operators'}, on_delete=django.db.models.deletion.PROTECT, related_name='shift_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='production_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='production_plan.productionplan', verbose_name='План производства'),
        ),
        migrations.AddField(
            model_name='shiftassignmentarchive',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='shiftassignmentarchive',
            name='production_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_assignments', to='production_plan.productionplan', verbose_name='План производства'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['shift_date'], name='shift_assig_shift_d_5fe4c1_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['status'], name='shift_assig_status_2e6b14_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['production_plan'], name='shift_assig_product_2690a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shiftassignment',
            unique_together={('shift_date', 'shift_type', 'machine_number')},
        ),
        migrations.AddIndex(
            model_name='shiftassignmentarchive',
            index=models.Index(fields=['original_id'], name='shift_assig_origina_0ccf59_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignmentarchive',
            index=models.Index(fields=['shift_date'], name='shift_assig_shift_d_ae0cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignmentarchive',
            index=models.Index(fields=['operator'], name='shift_assig_operato_df6aed_idx'),
        ),
    ]
