# Generated by Django 5.2 on 2025-05-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0002_alter_shiftassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='order_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование изделия'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='work_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид работ'),
        ),
    ]
