# Generated by Django 5.2 on 2025-04-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0002_alter_shiftassignment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftassignment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='part',
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='part_blueprint',
            field=models.FileField(blank=True, null=True, upload_to='part_blueprints/', verbose_name='Чертеж детали'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shiftassignmentarchive',
            name='part_blueprint',
            field=models.FileField(blank=True, null=True, upload_to='archived_blueprints/', verbose_name='Чертеж детали'),
        ),
    ]
