# Generated by Django 5.2 on 2025-04-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0003_remove_shiftassignment_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.IntegerField(unique=True, verbose_name='Номер станка')),
                ('status', models.CharField(choices=[('working', 'Работает'), ('idle', 'В простое'), ('setup', 'На переналадке'), ('repair', 'В ремонте')], max_length=10, verbose_name='Статус станка')),
                ('breakdown_time', models.DateTimeField(blank=True, help_text='Указывайте дату и время, когда станок сломался, если статус "В ремонте"', null=True, verbose_name='Дата и время поломки')),
                ('notes', models.TextField(blank=True, verbose_name='Дополнительные заметки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления статуса')),
            ],
            options={
                'verbose_name': 'Статус станка',
                'verbose_name_plural': 'Статусы станков',
                'ordering': ['machine_number'],
            },
        ),
    ]
