# Generated by Django 5.2 on 2025-05-14 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0005_directorproductionplan'),
        ('shift_assignment', '0003_shiftassignment_order_name_shiftassignment_work_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shiftassignment',
            name='shift_assig_status_2e6b14_idx',
        ),
        migrations.RemoveIndex(
            model_name='shiftassignment',
            name='shift_assig_product_2690a9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='shiftassignment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='shiftassignmentarchive',
            name='completion_time',
        ),
        migrations.RemoveField(
            model_name='shiftassignmentarchive',
            name='quality_status',
        ),
        migrations.AddField(
            model_name='shiftassignmentarchive',
            name='completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_archived_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Завершил'),
        ),
        migrations.AddField(
            model_name='shiftassignmentarchive',
            name='order_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование изделия'),
        ),
        migrations.AddField(
            model_name='shiftassignmentarchive',
            name='work_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид работ'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='shiftassignmentarchive',
            name='shift_date',
            field=models.DateField(db_index=True, verbose_name='Дата смены'),
        ),
        migrations.AlterField(
            model_name='shiftassignmentarchive',
            name='shift_type',
            field=models.CharField(choices=[('day', 'Дневная смена (08:00-20:00)'), ('night', 'Ночная смена (20:00-08:00)')], max_length=10, verbose_name='Тип смены'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['operator'], name='shift_assig_operato_b0f32b_idx'),
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='status',
        ),
    ]
