# Generated by Django 5.2 on 2025-04-28 08:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0004_alter_productionplan_options_and_more'),
        ('shift_assignment', '0004_machinestatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='MachineStatus',
        ),
        migrations.AlterModelOptions(
            name='shiftassignmentarchive',
            options={'ordering': ['-completed_at'], 'verbose_name': 'Архивное задание', 'verbose_name_plural': 'Архив заданий'},
        ),
        migrations.RemoveIndex(
            model_name='shiftassignmentarchive',
            name='shift_assig_origina_0ccf59_idx',
        ),
        migrations.RemoveIndex(
            model_name='shiftassignmentarchive',
            name='shift_assig_date_c443bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='shiftassignmentarchive',
            name='shift_assig_operato_df6aed_idx',
        ),
        migrations.RemoveField(
            model_name='shiftassignmentarchive',
            name='part_blueprint',
        ),
        migrations.RemoveField(
            model_name='shiftassignmentarchive',
            name='shift_duration',
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='order',
            field=models.CharField(default='unknow', max_length=255, verbose_name='Номер заказа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='part',
            field=models.CharField(default='unknow', max_length=255, verbose_name='Деталь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='production_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_assignments', to='production_plan.productionplan', verbose_name='План производства'),
        ),
        migrations.AddField(
            model_name='shiftassignmentarchive',
            name='production_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_assignments', to='production_plan.productionplan', verbose_name='План производства'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата задания'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='execution_status',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='machine_number',
            field=models.PositiveIntegerField(verbose_name='Номер станка'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='part_blueprint',
            field=models.FileField(blank=True, null=True, upload_to='part_blueprints/', verbose_name='Чертеж'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='shiftassignmentarchive',
            name='actual_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Фактическое количество'),
        ),
        migrations.AlterField(
            model_name='shiftassignmentarchive',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='shiftassignmentarchive',
            name='machine_number',
            field=models.PositiveIntegerField(verbose_name='Станок'),
        ),
        migrations.AlterField(
            model_name='shiftassignmentarchive',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='shiftassignmentarchive',
            name='original_id',
            field=models.PositiveIntegerField(verbose_name='ID задания'),
        ),
        migrations.AlterField(
            model_name='shiftassignmentarchive',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['date'], name='shift_assig_date_85ea26_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['execution_status'], name='shift_assig_executi_edc495_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['operator'], name='shift_assig_operato_b0f32b_idx'),
        ),
    ]
