# Generated by Django 5.2 on 2025-05-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0004_remove_shiftassignment_shift_assig_status_2e6b14_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='status',
            field=models.CharField(choices=[('assignment', 'Задание на смену'), ('completed', 'Выполненное задание')], db_index=True, default='assignment', max_length=20, verbose_name='Статус задания'),
        ),
    ]
