# Generated by Django 5.2 on 2025-04-29 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0005_delete_machinestatus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftassignment',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_assignments', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='shiftassignmentarchive',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_assignments', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Оператор'),
        ),
    ]
