# Generated by Django 5.2 on 2025-05-14 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0005_directorproductionplan'),
        ('shift_assignment', '0005_shiftassignment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['status'], name='shift_assig_status_2e6b14_idx'),
        ),
    ]
