# Generated by Django 5.2 on 2025-05-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0006_shiftassignment_shift_assig_status_2e6b14_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignmentarchive',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
