# Generated by Django 5.2 on 2025-05-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0006_alter_shiftassignment_operator_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shiftassignment',
            name='shift_assig_date_85ea26_idx',
        ),
        migrations.RemoveIndex(
            model_name='shiftassignment',
            name='shift_assig_executi_edc495_idx',
        ),
        migrations.RemoveIndex(
            model_name='shiftassignment',
            name='shift_assig_operato_b0f32b_idx',
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
