# Generated by Django 5.2 on 2025-05-02 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0004_alter_productionplan_options_and_more'),
        ('shift_assignment', '0007_remove_shiftassignment_shift_assig_date_85ea26_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftassignmentarchive',
            name='actual_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Фактически произведенное количество', null=True, verbose_name='Фактическое количество'),
        ),
        migrations.AlterField(
            model_name='shiftassignmentarchive',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='shiftassignmentarchive',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время завершения'),
        ),
        migrations.AlterField(
            model_name='shiftassignmentarchive',
            name='date',
            field=models.DateField(verbose_name='Дата выполнения задания'),
        ),
        migrations.AlterField(
            model_name='shiftassignmentarchive',
            name='machine_number',
            field=models.PositiveIntegerField(verbose_name='Номер станка'),
        ),
        migrations.AlterField(
            model_name='shiftassignmentarchive',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='Пользователь, выполнивший задание', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_assignments', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='shiftassignmentarchive',
            name='order',
            field=models.CharField(max_length=255, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='shiftassignmentarchive',
            name='original_id',
            field=models.PositiveIntegerField(help_text='ID задания из основной таблицы', verbose_name='ID оригинального задания'),
        ),
        migrations.AlterField(
            model_name='shiftassignmentarchive',
            name='production_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_assignments', to='production_plan.productionplan', verbose_name='Связанный план производства'),
        ),
        migrations.AlterField(
            model_name='shiftassignmentarchive',
            name='quality_check',
            field=models.BooleanField(default=False, help_text='Отметка о прохождении контроля качества', verbose_name='Проверка качества'),
        ),
        migrations.AlterField(
            model_name='shiftassignmentarchive',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Плановое количество'),
        ),
        migrations.AddIndex(
            model_name='shiftassignmentarchive',
            index=models.Index(fields=['original_id'], name='shift_assig_origina_0ccf59_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignmentarchive',
            index=models.Index(fields=['operator'], name='shift_assig_operato_df6aed_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignmentarchive',
            index=models.Index(fields=['completed_at'], name='shift_assig_complet_174747_idx'),
        ),
    ]
