# Generated by Django 5.2 on 2025-05-14 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0005_directorproductionplan'),
        ('shift_assignment', '0007_shiftassignmentarchive_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftassignmentarchive',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['completed_at'], name='shift_assig_complet_af197e_idx'),
        ),
    ]
