# Generated by Django 5.2 on 2025-05-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0008_remove_shiftassignmentarchive_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignmentarchive',
            name='drawing',
            field=models.FileField(blank=True, null=True, upload_to='archive_drawings/%Y/%m/%d/', verbose_name='Чертеж'),
        ),
    ]
