# Generated by Django 5.2 on 2025-05-15 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0009_shiftassignmentarchive_drawing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShiftAssignmentArchive',
        ),
    ]
