# Generated by Django 5.2 on 2025-05-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_assignment', '0010_delete_shiftassignmentarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftassignment',
            name='drawing',
            field=models.FileField(blank=True, null=True, upload_to='drawings/%Y/%m/%d/', verbose_name='Операционно-технологическая карта'),
        ),
    ]
