# Generated by Django 5.2 on 2025-05-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(help_text='Название компании-заказчика', max_length=255, verbose_name='Заказчик')),
                ('order', models.CharField(db_index=True, help_text='Уникальный идентификатор заказа', max_length=255, unique=True, verbose_name='Номер заказа')),
                ('product', models.CharField(help_text='Наименование производимого изделия', max_length=255, verbose_name='Изделие')),
                ('quantity', models.PositiveIntegerField(help_text='Общее количество изделий для производства', verbose_name='Количество')),
                ('drawing_number', models.CharField(blank=True, help_text='Номер чертежа или модели изделия', max_length=100, verbose_name='Чертеж/Модель')),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='0-100%', verbose_name='Процент выполнения')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'В работе'), ('on_hold', 'На паузе'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], db_index=True, default='draft', max_length=20, verbose_name='Статус плана')),
                ('deadline', models.DateField(help_text='Планируемая дата завершения производства', verbose_name='Срок выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о плане', verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Производственный план',
                'verbose_name_plural': 'Производственные планы',
                'ordering': ['-deadline'],
            },
        ),
    ]
