# Generated by Django 5.2 on 2025-05-05 21:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(help_text='Название компании-заказчика', max_length=255, verbose_name='Заказчик')),
                ('order', models.CharField(db_index=True, help_text='Уникальный идентификатор заказа', max_length=255, unique=True, verbose_name='Номер заказа')),
                ('product', models.CharField(help_text='Наименование производимого изделия', max_length=255, verbose_name='Изделие')),
                ('quantity', models.PositiveIntegerField(help_text='Общее количество изделий для производства', verbose_name='Количество')),
                ('drawing_number', models.CharField(blank=True, help_text='Номер чертежа или модели изделия', max_length=100, verbose_name='Чертеж/Модель')),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='0-100%', verbose_name='Процент выполнения')),
                ('is_completed', models.BooleanField(default=False, help_text='Отметьте, если план выполнен полностью', verbose_name='Завершён')),
                ('deadline', models.DateField(help_text='Планируемая дата завершения производства', verbose_name='Срок выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Производственный план',
                'verbose_name_plural': 'Производственные планы',
                'ordering': ['-deadline'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название материала или комплектующего', max_length=255, verbose_name='Наименование')),
                ('quantity', models.PositiveIntegerField(help_text='Количество поставляемых единиц', verbose_name='Количество')),
                ('expected_date', models.DateField(help_text='Планируемая дата поставки', verbose_name='Ожидаемая дата')),
                ('received_date', models.DateField(blank=True, help_text='Дата фактического получения', null=True, verbose_name='Фактическая дата')),
                ('status', models.CharField(choices=[('pending', 'Ожидается'), ('delivered', 'Доставлено'), ('canceled', 'Отменено')], db_index=True, default='pending', max_length=20, verbose_name='Статус поставки')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о поставке', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
                'ordering': ['-expected_date'],
            },
        ),
    ]
