# Generated by Django 5.2 on 2025-05-06 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='created_by',
            field=models.ForeignKey(help_text='Пользователь, создавший план', on_delete=django.db.models.deletion.PROTECT, related_name='created_plans', to=settings.AUTH_USER_MODEL, verbose_name='Автор плана'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['order'], name='production__order_75327a_idx'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['customer'], name='production__custome_915e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['deadline'], name='production__deadlin_625b54_idx'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['status'], name='production__status_959ede_idx'),
        ),
    ]
