# Generated by Django 5.2 on 2025-04-19 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название поставки')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('expected_date', models.DateField(verbose_name='Ожидаемая дата поставки')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Дата получения')),
                ('status', models.CharField(choices=[('upcoming', 'Ожидается'), ('received', 'Получена'), ('canceled', 'Отменена')], max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
                'ordering': ['-expected_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='productionplan',
            options={'verbose_name': 'План производства', 'verbose_name_plural': 'Планы производства'},
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='customer',
            field=models.CharField(max_length=255, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='deadline',
            field=models.DateTimeField(verbose_name='Срок отгрузки'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='order',
            field=models.CharField(max_length=255, verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='plan',
            field=models.FileField(upload_to='production_plans/', verbose_name='План производства'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='product',
            field=models.CharField(max_length=255, verbose_name='Продукция'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='Процент выполнения'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_plans', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользователем'),
        ),
    ]
