# Generated by Django 5.2 on 2025-05-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Отметьте, если план выполнен полностью', verbose_name='Завершён'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='notes',
            field=models.TextField(blank=True, help_text='Дополнительные комментарии к плану', verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('cancelled', 'Отменено')], db_index=True, default='planned', help_text='Статус выполнения плана', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['order'], name='production__order_75327a_idx'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['customer'], name='production__custome_915e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['deadline'], name='production__deadlin_625b54_idx'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['is_completed'], name='production__is_comp_d2340e_idx'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['status'], name='production__status_959ede_idx'),
        ),
    ]
