# Generated by Django 5.2 on 2025-05-05 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='created_by',
            field=models.ForeignKey(help_text='Пользователь, создавший план', on_delete=django.db.models.deletion.PROTECT, related_name='created_plans', to=settings.AUTH_USER_MODEL, verbose_name='Автор плана'),
        ),
        migrations.AddField(
            model_name='supply',
            name='production_plan',
            field=models.ForeignKey(help_text='Связанный производственный план', on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='production_plan.productionplan', verbose_name='Производственный план'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['order'], name='production__order_75327a_idx'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['customer'], name='production__custome_915e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['deadline'], name='production__deadlin_625b54_idx'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['is_completed'], name='production__is_comp_d2340e_idx'),
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['status'], name='production__status_ef0086_idx'),
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['expected_date'], name='production__expecte_21f49e_idx'),
        ),
        migrations.AddIndex(
            model_name='supply',
            index=models.Index(fields=['production_plan'], name='production__product_482584_idx'),
        ),
    ]
