# Generated by Django 5.2 on 2025-05-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0002_productionplan_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionplan',
            name='notes',
        ),
    ]
