# Generated by Django 5.2 on 2025-04-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0002_supply_alter_productionplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершён'),
        ),
    ]
