# Generated by Django 5.2 on 2025-05-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0003_remove_productionplan_notes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productionplan',
            name='production__order_75327a_idx',
        ),
        migrations.RemoveIndex(
            model_name='productionplan',
            name='production__is_comp_d2340e_idx',
        ),
        migrations.RemoveIndex(
            model_name='productionplan',
            name='production__status_959ede_idx',
        ),
        migrations.RemoveField(
            model_name='productionplan',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='productionplan',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productionplan',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='productionplan',
            name='status',
        ),
        migrations.AddField(
            model_name='productionplan',
            name='order_name',
            field=models.CharField(blank=True, db_index=True, help_text='Наименование производственного заказа', max_length=255, null=True, verbose_name='Наименование заказа'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['order_name'], name='production__order_n_20a4f5_idx'),
        ),
    ]
