# Generated by Django 5.2 on 2025-04-28 08:09

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0003_productionplan_is_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionplan',
            options={'ordering': ['-deadline'], 'verbose_name': 'План производства', 'verbose_name_plural': 'Планы производства'},
        ),
        migrations.AddField(
            model_name='productionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 28, 13, 0), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='supply',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='supply',
            name='production_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='production_plan.productionplan', verbose_name='План производства'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_plans', to=settings.AUTH_USER_MODEL, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='deadline',
            field=models.DateField(verbose_name='Срок отгрузки'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='0-100%', verbose_name='Процент выполнения'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_plans', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='expected_date',
            field=models.DateField(verbose_name='Ожидаемая дата'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Ожидается'), ('received', 'Получена'), ('canceled', 'Отменена')], default='upcoming', max_length=10, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['order'], name='production__order_75327a_idx'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['customer'], name='production__custome_915e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='productionplan',
            index=models.Index(fields=['deadline'], name='production__deadlin_625b54_idx'),
        ),
    ]
