# Generated by Django 5.2 on 2025-05-10 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0004_remove_productionplan_production__order_75327a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('production_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='production_plan.productionplan')),
            ],
        ),
    ]
