# Generated by Django 5.2 on 2025-05-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0005_directorproductionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplan',
            name='drawing_number',
            field=models.CharField(blank=True, help_text='Номер операционно-технологической карты или модели изделия', max_length=100, verbose_name='Операционно-технологическая карта'),
        ),
    ]
