# Generated by Django 5.2 on 2025-05-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0006_alter_productionplan_drawing_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='customer',
            field=models.CharField(max_length=255, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='deadline',
            field=models.DateField(verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='drawing_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Чертеж'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='order_name',
            field=models.CharField(db_index=True, default='Без названия', help_text='Наименование производственного заказа', max_length=255, verbose_name='Наименование заказа'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='product',
            field=models.CharField(max_length=255, verbose_name='Изделие'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
