# Generated by Django 5.2 on 2025-06-11 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0007_alter_productionplan_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplan',
            name='customer',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Заказчик'),
        ),
    ]
